using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Morphological_Analyzer
{
    class WordTrans1
    {
        public static string Transtyle(string InWord)
        {

            InWord = InWord.Replace("ஐ", "ai");
            InWord = InWord.Replace("அ", "a");
            InWord = InWord.Replace("ஆ", "ā");
            InWord = InWord.Replace("இ", "i");
            InWord = InWord.Replace("ஈ", "ī");
            InWord = InWord.Replace("உ", "u");
            InWord = InWord.Replace("ஊ", "ū");
            InWord = InWord.Replace("எ", "e");
            InWord = InWord.Replace("ஏ", "ē");
          //  InWord = InWord.Replace("ஐ", "ai");
            InWord = InWord.Replace("ஒ", "o");
            InWord = InWord.Replace("ஓ", "ō");
            InWord = InWord.Replace("ஔ", "au");
            InWord = InWord.Replace("ஃ", "ḵ");
            InWord = InWord.Replace("ஸ்ரீ", "šrī");


            InWord = InWord.Replace("க்", "k");
            InWord = InWord.Replace("ங்", "ṅ");
            InWord = InWord.Replace("ச்", "c");
            InWord = InWord.Replace("ஞ்", "ñ");
            InWord = InWord.Replace("ட்", "ṭ");
            InWord = InWord.Replace("ண்", "ṇ");
            InWord = InWord.Replace("த்", "t");
            InWord = InWord.Replace("ந்", "n");
            InWord = InWord.Replace("ப்", "p");
            InWord = InWord.Replace("ம்", "m");
            InWord = InWord.Replace("ய்", "y");
            InWord = InWord.Replace("ர்", "r");
            InWord = InWord.Replace("ல்", "l");
            InWord = InWord.Replace("வ்", "v");
            InWord = InWord.Replace("ழ்", "ḻ");
            InWord = InWord.Replace("ள்", "ḷ");
            InWord = InWord.Replace("ற்", "ṟ");
            InWord = InWord.Replace("ன்", "ṉ");
            InWord = InWord.Replace("ஜ்", "j");
            InWord = InWord.Replace("ஷ்", "ṣ");
            InWord = InWord.Replace("ஸ்", "s");
            InWord = InWord.Replace("ஹ்", "h");



            InWord = InWord.Replace("கா", "kā");
            InWord = InWord.Replace("ஙா", "ṅā");
            InWord = InWord.Replace("சா", "cā");
            InWord = InWord.Replace("ஞா", "ñā");
            InWord = InWord.Replace("டா", "ṭā");
            InWord = InWord.Replace("ணா", "ṇā");
            InWord = InWord.Replace("தா", "tā");
            InWord = InWord.Replace("நா", "nā");
            InWord = InWord.Replace("பா", "pā");
            InWord = InWord.Replace("மா", "mā");
            InWord = InWord.Replace("யா", "yā");
            InWord = InWord.Replace("ரா", "rā");
            InWord = InWord.Replace("லா", "lā");
            InWord = InWord.Replace("வா", "vā");
            InWord = InWord.Replace("ழா", "ḻā");
            InWord = InWord.Replace("ளா", "ḷā");
            InWord = InWord.Replace("றா", "ṟā");
            InWord = InWord.Replace("னா", "ṉā");
            InWord = InWord.Replace("ஜா", "jā");
            InWord = InWord.Replace("ஷா", "ṣā");
            InWord = InWord.Replace("ஸா", "sā");
            InWord = InWord.Replace("ஹா", "hā");


            InWord = InWord.Replace("கி", "ki");
            InWord = InWord.Replace("ஙி", "ṅi");
            InWord = InWord.Replace("சி", "ci");
            InWord = InWord.Replace("ஞி", "ñi");
            InWord = InWord.Replace("டி", "ṭi");
            InWord = InWord.Replace("ணி", "ṇi");
            InWord = InWord.Replace("தி", "ti");
            InWord = InWord.Replace("நி", "ni");
            InWord = InWord.Replace("பி", "pi");
            InWord = InWord.Replace("மி", "mi");
            InWord = InWord.Replace("யி", "yi");
            InWord = InWord.Replace("ரி", "ri");
            InWord = InWord.Replace("லி", "li");
            InWord = InWord.Replace("வி", "vi");
            InWord = InWord.Replace("ழி", "ḻi");
            InWord = InWord.Replace("ளி", "ḷi");
            InWord = InWord.Replace("றி", "ṟi");
            InWord = InWord.Replace("னி", "ṉi");
            InWord = InWord.Replace("ஜி", "ji");
            InWord = InWord.Replace("ஷி", "ṣi");
            InWord = InWord.Replace("ஸி", "si");
            InWord = InWord.Replace("ஹி", "hi");

            InWord = InWord.Replace("கீ", "kī");
            InWord = InWord.Replace("ஙீ", "ṅī");
            InWord = InWord.Replace("சீ", "cī");
            InWord = InWord.Replace("ஞீ", "ñī");
            InWord = InWord.Replace("டீ", "ṭī");
            InWord = InWord.Replace("ணீ", "ṇī");
            InWord = InWord.Replace("தீ", "tī");
            InWord = InWord.Replace("நீ", "nī");
            InWord = InWord.Replace("பீ", "pī");
            InWord = InWord.Replace("மீ", "mī");
            InWord = InWord.Replace("யீ", "yī");
            InWord = InWord.Replace("ரீ", "rī");
            InWord = InWord.Replace("லீ", "lī");
            InWord = InWord.Replace("வீ", "vī");
            InWord = InWord.Replace("ழீ", "ḻī");
            InWord = InWord.Replace("ளீ", "ḷī");
            InWord = InWord.Replace("றீ", "ṟī");
            InWord = InWord.Replace("னீ", "ṉī");
            InWord = InWord.Replace("ஜீ", "jī");
            InWord = InWord.Replace("ஷீ", "ṣī");
            InWord = InWord.Replace("ஸீ", "sī");
            InWord = InWord.Replace("ஹீ", "hī");

            InWord = InWord.Replace("கு", "ku");
            InWord = InWord.Replace("ஙு", "ṅu");
            InWord = InWord.Replace("சு", "cu");
            InWord = InWord.Replace("ஞு", "ñu");
            InWord = InWord.Replace("டு", "ṭu");
            InWord = InWord.Replace("ணு", "ṇu");
            InWord = InWord.Replace("து", "tu");
            InWord = InWord.Replace("நு", "nu");
            InWord = InWord.Replace("பு", "pu");
            InWord = InWord.Replace("மு", "mu");
            InWord = InWord.Replace("யு", "yu");
            InWord = InWord.Replace("ரு", "ru");
            InWord = InWord.Replace("லு", "lu");
            InWord = InWord.Replace("வு", "vu");
            InWord = InWord.Replace("ழு", "ḻu");
            InWord = InWord.Replace("ளு", "ḷu");
            InWord = InWord.Replace("று", "ṟu");
            InWord = InWord.Replace("னு", "ṉu");
            InWord = InWord.Replace("ஜு", "ju");
            InWord = InWord.Replace("ஷு", "ṣu");
            InWord = InWord.Replace("ஸு", "su");
            InWord = InWord.Replace("ஹு", "hu");

            InWord = InWord.Replace("கூ", "kū");
            InWord = InWord.Replace("ஙூ", "ṅū");
            InWord = InWord.Replace("சூ", "cū");
            InWord = InWord.Replace("ஞூ", "ñū");
            InWord = InWord.Replace("டூ", "ṭū");
            InWord = InWord.Replace("ணூ", "ṇū");
            InWord = InWord.Replace("தூ", "tū");
            InWord = InWord.Replace("நூ", "nū");
            InWord = InWord.Replace("பூ", "pū");
            InWord = InWord.Replace("மூ", "mū");
            InWord = InWord.Replace("யூ", "yū");
            InWord = InWord.Replace("ரூ", "rū");
            InWord = InWord.Replace("லூ", "lū");
            InWord = InWord.Replace("வூ", "vū");
            InWord = InWord.Replace("ழூ", "ḻū");
            InWord = InWord.Replace("ளூ", "ḷū");
            InWord = InWord.Replace("றூ", "ṟū");
            InWord = InWord.Replace("னூ", "ṉū");
            InWord = InWord.Replace("ஜூ", "jū");
            InWord = InWord.Replace("ஷூ", "ṣū");
            InWord = InWord.Replace("ஸூ", "sū");
            InWord = InWord.Replace("ஹூ", "hū");

            InWord = InWord.Replace("கெ", "ke");
            InWord = InWord.Replace("ஙெ", "ṅe");
            InWord = InWord.Replace("செ", "ce");
            InWord = InWord.Replace("ஞெ", "ñe");
            InWord = InWord.Replace("டெ", "ṭe");
            InWord = InWord.Replace("ணெ", "ṇe");
            InWord = InWord.Replace("தெ", "te");
            InWord = InWord.Replace("நெ", "ne");
            InWord = InWord.Replace("பெ", "pe");
            InWord = InWord.Replace("மெ", "me");
            InWord = InWord.Replace("யெ", "ye");
            InWord = InWord.Replace("ரெ", "re");
            InWord = InWord.Replace("லெ", "le");
            InWord = InWord.Replace("வெ", "ve");
            InWord = InWord.Replace("ழெ", "ḻe");
            InWord = InWord.Replace("ளெ", "ḷe");
            InWord = InWord.Replace("றெ", "ṟe");
            InWord = InWord.Replace("னெ", "ṉe");
            InWord = InWord.Replace("ஜெ", "je");
            InWord = InWord.Replace("ஷெ", "ṣe");
            InWord = InWord.Replace("ஸெ", "se");
            InWord = InWord.Replace("ஹெ", "he");

            InWord = InWord.Replace("கே", "kē");
            InWord = InWord.Replace("ஙே", "ṅē");
            InWord = InWord.Replace("சே", "cē");
            InWord = InWord.Replace("ஞே", "ñē");
            InWord = InWord.Replace("டே", "ṭē");
            InWord = InWord.Replace("ணே", "ṇē");
            InWord = InWord.Replace("தே", "tē");
            InWord = InWord.Replace("நே", "nē");
            InWord = InWord.Replace("பே", "pē");
            InWord = InWord.Replace("மே", "mē");
            InWord = InWord.Replace("யே", "yē");
            InWord = InWord.Replace("ரே", "rē");
            InWord = InWord.Replace("லே", "lē");
            InWord = InWord.Replace("வே", "vē");
            InWord = InWord.Replace("ழே", "ḻē");
            InWord = InWord.Replace("ளே", "ḷē");
            InWord = InWord.Replace("றே", "ṟē");
            InWord = InWord.Replace("னே", "ṉē");
            InWord = InWord.Replace("ஜே", "jē");
            InWord = InWord.Replace("ஷே", "ṣē");
            InWord = InWord.Replace("ஸே", "sē");
            InWord = InWord.Replace("ஹே", "hē");

            InWord = InWord.Replace("கை", "kai");
            InWord = InWord.Replace("ஙை", "ṅai");
            InWord = InWord.Replace("சை", "cai");
            InWord = InWord.Replace("ஞை", "ñai");
            InWord = InWord.Replace("டை", "ṭai");
            InWord = InWord.Replace("ணை", "ṇai");
            InWord = InWord.Replace("தை", "tai");
            InWord = InWord.Replace("நை", "nai");
            InWord = InWord.Replace("பை", "pai");
            InWord = InWord.Replace("மை", "mai");
            InWord = InWord.Replace("யை", "yai");
            InWord = InWord.Replace("ரை", "rai");
            InWord = InWord.Replace("லை", "lai");
            InWord = InWord.Replace("வை", "vai");
            InWord = InWord.Replace("ழை", "ḻai");
            InWord = InWord.Replace("ளை", "ḷai");
            InWord = InWord.Replace("றை", "ṟai");
            InWord = InWord.Replace("னை", "ṉai");
            InWord = InWord.Replace("ஜை", "jai");
            InWord = InWord.Replace("ஷை", "ṣai");
            InWord = InWord.Replace("ஸை", "sai");
            InWord = InWord.Replace("ஹை", "hai");

            InWord = InWord.Replace("கொ", "ko");
            InWord = InWord.Replace("ஙொ", "ṅo");
            InWord = InWord.Replace("சொ", "co");
            InWord = InWord.Replace("ஞொ", "ño");
            InWord = InWord.Replace("டொ", "ṭo");
            InWord = InWord.Replace("ணொ", "ṇo");
            InWord = InWord.Replace("தொ", "to");
            InWord = InWord.Replace("நொ", "no");
            InWord = InWord.Replace("பொ", "po");
            InWord = InWord.Replace("மொ", "mo");
            InWord = InWord.Replace("யொ", "yo");
            InWord = InWord.Replace("ரொ", "ro");
            InWord = InWord.Replace("லொ", "lo");
            InWord = InWord.Replace("வொ", "vo");
            InWord = InWord.Replace("ழொ", "ḻo");
            InWord = InWord.Replace("ளொ", "ḷo");
            InWord = InWord.Replace("றொ", "ṟo");
            InWord = InWord.Replace("னொ", "ṉo");
            InWord = InWord.Replace("ஜொ", "jo");
            InWord = InWord.Replace("ஷொ", "ṣo");
            InWord = InWord.Replace("ஸொ", "so");
            InWord = InWord.Replace("ஹொ", "ho");

            InWord = InWord.Replace("கோ", "kō");
            InWord = InWord.Replace("ஙோ", "ṅō");
            InWord = InWord.Replace("சோ", "cō");
            InWord = InWord.Replace("ஞோ", "ñō");
            InWord = InWord.Replace("டோ", "ṭō");
            InWord = InWord.Replace("ணோ", "ṇō");
            InWord = InWord.Replace("தோ", "tō");
            InWord = InWord.Replace("நோ", "nō");
            InWord = InWord.Replace("போ", "pō");
            InWord = InWord.Replace("மோ", "mō");
            InWord = InWord.Replace("யோ", "yō");
            InWord = InWord.Replace("ரோ", "rō");
            InWord = InWord.Replace("லோ", "lō");
            InWord = InWord.Replace("வோ", "vō");
            InWord = InWord.Replace("ழோ", "ḻō");
            InWord = InWord.Replace("ளோ", "ḷō");
            InWord = InWord.Replace("றோ", "ṟō");
            InWord = InWord.Replace("னோ", "ṉō");
            InWord = InWord.Replace("ஜோ", "jō");
            InWord = InWord.Replace("ஷோ", "ṣō");
            InWord = InWord.Replace("ஸோ", "sō");
            InWord = InWord.Replace("ஹோ", "hō");

            InWord = InWord.Replace("கௌ", "kau");
            InWord = InWord.Replace("ஙௌ", "ṅau");
            InWord = InWord.Replace("சௌ", "cau");
            InWord = InWord.Replace("ஞௌ", "ñau");
            InWord = InWord.Replace("டௌ", "ṭau");
            InWord = InWord.Replace("ணௌ", "ṇau");
            InWord = InWord.Replace("தௌ", "tau");
            InWord = InWord.Replace("நௌ", "nau");
            InWord = InWord.Replace("பௌ", "pau");
            InWord = InWord.Replace("மௌ", "mau");
            InWord = InWord.Replace("யௌ", "yau");
            InWord = InWord.Replace("ரௌ", "rau");
            InWord = InWord.Replace("லௌ", "lau");
            InWord = InWord.Replace("வௌ", "vau");
            InWord = InWord.Replace("ழௌ", "ḻau");
            InWord = InWord.Replace("ளௌ", "ḷau");
            InWord = InWord.Replace("றௌ", "ṟau");
            InWord = InWord.Replace("னௌ", "ṉau");
            InWord = InWord.Replace("ஜௌ", "jau");
            InWord = InWord.Replace("ஷௌ", "ṣau");
            InWord = InWord.Replace("ஸௌ", "sau");
            InWord = InWord.Replace("ஹௌ", "hau");

            InWord = InWord.Replace("க", "ka");
            InWord = InWord.Replace("ங", "ṅa");
            InWord = InWord.Replace("ச", "ca");
            InWord = InWord.Replace("ஞ", "ña");
            InWord = InWord.Replace("ட", "ṭa");
            InWord = InWord.Replace("ண", "ṇa");
            InWord = InWord.Replace("த", "ta");
            InWord = InWord.Replace("ந", "na");
            InWord = InWord.Replace("ப", "pa");
            InWord = InWord.Replace("ம", "ma");
            InWord = InWord.Replace("ய", "ya");
            InWord = InWord.Replace("ர", "ra");
            InWord = InWord.Replace("ல", "la");
            InWord = InWord.Replace("வ", "va");
            InWord = InWord.Replace("ழ", "ḻa");
            InWord = InWord.Replace("ள", "ḷa");
            InWord = InWord.Replace("ற", "ṟa");
            InWord = InWord.Replace("ஷ", "ṣa");
            InWord = InWord.Replace("ஜ", "ja");
            InWord = InWord.Replace("ன", "ṉa");
            InWord = InWord.Replace("ஸ", "sa");
            InWord = InWord.Replace("ஹ", "ha");

            InWord = InWord.Replace("க", "ka");
            InWord = InWord.Replace("ங", "ṅa");
            InWord = InWord.Replace("ச", "ca");
            InWord = InWord.Replace("ஞ", "ña");
            InWord = InWord.Replace("ட", "ṭa");
            InWord = InWord.Replace("ண", "ṇa");
            InWord = InWord.Replace("த", "ta");
            InWord = InWord.Replace("ந", "na");
            InWord = InWord.Replace("ப", "pa");
            InWord = InWord.Replace("ம", "ma");
            InWord = InWord.Replace("ய", "ya");
            InWord = InWord.Replace("ர", "ra");
            InWord = InWord.Replace("ல", "la");
            InWord = InWord.Replace("வ", "va");
            InWord = InWord.Replace("ழ", "ḻa");
            InWord = InWord.Replace("ள", "ḷa");
            InWord = InWord.Replace("ற", "ṟa");
            InWord = InWord.Replace("ஷ", "ṣa");
            InWord = InWord.Replace("ஜ", "ja");
            InWord = InWord.Replace("ன", "ṉa");
            InWord = InWord.Replace("ஸ", "sa");
            InWord = InWord.Replace("ஹ", "ha");

            return InWord;

        }

    }
}
